### ISSUE TITLE
DNFdragora – Optimal use of the screen's surface

### ISSUE THREAD

**Issue by Ricky-Tigg** [libyui/libyui-gtk#63]
libyui/libyui – [#125](https://github.com/libyui/libyui/issues/125#issuecomment-431695875) – ➙ libyui/libyui-gtk

**Comment by ancorgs** [comment]
Since the Gtk backend is not developed or maintained by the YaST Team at SUSE, I'm adding the "other-maintainer" label to this in order to help filtering the various list of issues.
