### ISSUE TITLE
libyui.so.12 and YLabel::setAutoWrap()

### ISSUE THREAD

**Issue by shundhammer** [libyui/libyui-gtk#69]
FYI: New libyui feature: Now supporting auto-wrapping for label widgets.

See https://github.com/libyui/libyui/pull/165

Since that made some new virtual methods necessary in YLabel and in YDialog, we had to bump the .so version to 12.

**Comment by anaselli** [comment]
thank you very much for your info and documentation. 
I need to test the Qt and ncurses ouptut that here doesn't seem to be as expected.

**Comment by shundhammer** [comment]
Please be aware that some of the dependent PRs are still on the way.

**Comment by anaselli** [comment]
ah ok that's could be why :)

**Comment by shundhammer** [comment]
Okay, they are now all merged, and everything is building without a problem in OBS.

https://build.opensuse.org/project/show/YaST:Head

**Comment by anaselli** [comment]
thank you I'll have a look at it asap

**Comment by anaselli** [comment]
Please merge the libyui/libyui-gtk/pull/72, so that we can close this bug and tag a new release.
Thanks

**Comment by anaselli** [comment]
@shundhammer could you please release or just tag new libyui, libyui-qt and libyui-ncurses? I need them to work on bindings and propose a new patch for libyui-mga plugin
thanks
