### ISSUE TITLE
Dialogs created by createMainWindow fail to manage size and resize

### ISSUE THREAD

**Issue by anaselli** [libyui/libyui-gtk#76]
When a dialog is create by createMainDialog followed errors occurred:
```
<ERR> [Gtk] libyui-gtk:0 (): gtk_window_set_default_size: assertion 'width >= -1' failed
<ERR> [Gtk] libyui-gtk:0 (): gtk_window_resize: assertion 'width > 0' failed
```

That seems due to -80 returned by [displayWidth and displayHeight](https://github.com/libyui/libyui-gtk/blob/master/src/YGUI.cc#L620-L650) which forces a fullscreen view.

Another issue related but to be investigated more is that the windows cannot be resized by height under a limit that often people say being bigger than their monitor height.

See related bug [here](https://github.com/manatools/dnfdragora/issues/164) and [here](https://github.com/manatools/dnfdragora/issues/175).

**Comment by anaselli** [comment]
I decided to try using the same way for defaultHeight and defaultWidth as in QT, compared to what we have before the windows, for what i tested, start at the same size and position of libyui-qt.

For what resizing concern i found widget that cannot be downsize by height, such as comboboxes, richtext and selectionboxes for instance. So i will ask for merge next PR to have a better behavior and see people feedbacks.

**Comment by elFarto** [comment]
After actually taking a look at that code properly the cause is obvious. They should be using monitor.width and monitor.height, not .x and .y, as those just have the offsets of the monitor in the current display.

**Comment by anaselli** [comment]
Yes but that was not enough, the ratio imo was wrong and output windows was ugly, now with the above patch should be ok.
@shundhammer could you please review this patch?
